#!/bin/sh
MONTHLY_REVENUE=2000
AGENT_COUNT=`./round-status.sh |wc -l`
TOK_RATING=$((25/$AGENT_COUNT))
TPM=500 # tokens per message
MPM=$((60*60*24*304*25/10/$TPM))

BRONZE_RATIO=1000 # 50%
BRONZE_MESSAGES=$(($MPM*$BRONZE_RATIO/$MONTHLY_REVENUE))
BRONZE_USERS=200
BRONZE_MESSAGES=$(($BRONZE_MESSAGES/$BRONZE_USERS))
BRONZE=5

SILVER_RATIO=600  # 30%
SILVER_MESSAGES=$(($MPM*$SILVER_RATIO/$MONTHLY_REVENUE))
SILVER_USERS=60
SILVER_MESSAGES=$(($SILVER_MESSAGES/$SILVER_USERS))
SILVER=10

GOLD_RATIO=400    # 20%
GOLD_MESSAGES=$(($MPM*$GOLD_RATIO/$MONTHLY_REVENUE))
GOLD_USERS=20
GOLD_MESSAGES=$(($GOLD_MESSAGES/$GOLD_USERS))
GOLD=20

echo "Messages Per Month: $MPM"
echo "Gold ($GOLD_MESSAGES requests/mo): \$$GOLD/mo"
echo "Silver ($SILVER_MESSAGES requests/mo): \$$SILVER/mo"
echo "Bronze ($BRONZE_MESSAGES requests/mo): \$$BRONZE/mo"
echo "Free (10 requests/day): \$0/mo"
